# Documentation configuration for Running-Calculator.

INHERIT: .mkdocs-shared/shared/mkdocs.base.yml

site_name: 'Running Calculator'
site_description: 'A running distance and speed command line interface. Measures in metric and imperial units, as well as marathons and half-marathons.'
site_author: willtheorangeguy
site_url: https://williamvdg.me/Running-Calculator/

repo_url: https://github.com/willtheorangeguy/Running-Calculator
repo_name: willtheorangeguy/Running-Calculator
edit_uri: edit/main/docs/

copyright: Copyright &copy; willtheorangeguy

nav:
  - Home: index.md
  - 'Quickstart': 'quickstart.md'
  - 'Installation': 'installation.md'
  - 'Architecture': 'architecture.md'
  - 'Development': 'development.md'
  - 'FAQ': 'faq.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Roadmap': 'roadmap.md'
  - 'Running-Calculator': 'internal/known-issues.md'
  - 'Units': 'units.md'
  - Changelog: changelog.md
  - License: license.md
  - Contributing: https://github.com/willtheorangeguy/.github/blob/main/CONTRIBUTING.md
  - Code of Conduct: https://github.com/willtheorangeguy/.github/blob/main/CODE_OF_CONDUCT.md
  - Security: https://github.com/willtheorangeguy/.github/blob/main/SECURITY.md

exclude_docs: |
  docs.instructions.md